### ISSUE TITLE
Drivers problems

### ISSUE THREAD

**Issue by mmonstudies** [Tom-Hirschberger/MMM-Temperature#12]
HI sorry for asking noobie questions but I am having troubles with the DHT11 sensor and displaying the values in MagicMirror.
even if I use my own script in python which works properly outside the MM I receive a message as follows:
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver
Thought you might be helpful, thanks in advance!

**Comment by Tom-Hirschberger** [comment]
Hi,

it looks this is an unsolved problem with the graphics stack on 64bit Raspberry OS and there are open topics in a couple of locations:

[Mirror Forum](https://forum.magicmirror.builders/topic/17013/mesa-loader-failed-to-open-kms_swrast/5?_=1673550499793)
[Raspberry Forum](https://forums.raspberrypi.com/viewtopic.php?t=338778)

But I see no error that causes the Python script of DHT11 to fail.

Does the script return any value if you run it on the console?

**Comment by Tom-Hirschberger** [comment]
Hi,

i saw your [issue](https://github.com/ryck/MMM-DHT-Sensor/issues/31) in MMM-DHT-Sensor today. As i read in the other issue you connected the sensor to the eight pin in the left side (network port to the user) and configured your pin setting according to [pinout](https://pi4j.com/1.2/pins/model-b-rev2.html) of wiringpi (which is identical to Pi4J) to 3.
This module and MMM-DHT-Sensor use the official [pinout](https://linuxhint.com/gpio-pinout-raspberry-pi/). 

If you use the eight pin it will be GPIO 22 in your case. 
If you really use GPIO 3 make sure to disable the I2C in the Raspberry config as GPIO 3 is used by the SDL of the I2C bus.

**Comment by Tom-Hirschberger** [comment]
As there is no new information and I can see no relationship of the problem and this module I will close the ticket for now.
Feel free to re-open if the problem is still present with this module.
