### ISSUE TITLE
It is showing couldn't create tree dir for that git cloning link

### ISSUE THREAD

**Issue by ALLADIRAMPRASAD** [Tom-Hirschberger/MMM-Temperature#13]
Please solve my issue

**Comment by Tom-Hirschberger** [comment]
Hi,

Sounds to my like you are trying to clone to a directory you do not have write permissions in.
How and where do you try to clone?

**Comment by ALLADIRAMPRASAD** [comment]
Hi.
I need help
I want to add a temparature module
And i have run all the commands and done properly
And now i need add code in config.js file.
But after adding while saving it is showing permission denied.so what
should I do now?

**Comment by Tom-Hirschberger** [comment]
Sorry, but i do not think that your problem is related to the module and i need more information to provide help.
What kind of system are you using? A Raspberry?
What operating system are you using? Raspberry OS? 32 Bit or 64Bit? Buster or Bullseye?
How did you install the MagicMirror software? Manuall Installation or the script of sdetweil?
Do you use the default user (pi) or a different one?
How did you install this module?

**Comment by ALLADIRAMPRASAD** [comment]
I'm using Rasp3B+ .
Using laptop with windows 13 .
Using 32bit OS.
Used bullseye.
Magic'mirror installation is  done manually through commands.
I'm using default pi.
And DHT module installation also done through manually.
......... thanks for writing me back and helping me..

**Comment by Tom-Hirschberger** [comment]
If you have not put to much afford into the installation till now i would suggest to re-install the MagicMirror software with the script of sdetweil again (https://github.com/sdetweil/MagicMirror_scripts).
The script takes care of the right node and npm version, checks the permissions, deactivates the screen blanking and if wanted the autostart.

I see two possible ways why the config.js file is not writeable. Either the permissions are wrong (maybe cause of a wrong sudo during the installation) or your SD card may be corrupt.

**Comment by Tom-Hirschberger** [comment]
Hi,

did you try the reinstall or is there anything else I can do to help?

**Comment by Tom-Hirschberger** [comment]
As there is no progress i will close the ticket for now. Feel free to re-open it if you have any detailed question or try opening a thread in the forum [https://forum.magicmirror.builders/](https://forum.magicmirror.builders/).
I am active there as well and will help wherever i can.
