### ISSUE TITLE
BME280 Script error

### ISSUE THREAD

**Issue by BKeyport** [Tom-Hirschberger/MMM-Temperature#8]
the script for the BME sensor is using the wrong I2C address, current i2c address for BME280 is 0x77, not 0x76.

**Comment by Tom-Hirschberger** [comment]
Hi,
most of my sensors use 0x76 as address (AZ-Delivery) and require to solder a jumper bridge to use 0x77 as address. I released a new version a view minutes ago which contains a modified bme280 script that supports setting the i2c address as an commandline option.
This example should work for your case:
```json5
		{
			module: "MMM-Temperature",
			position: "bottom_right",
			config: {
				sensors: [
					{
					    name: "Sensor One",
					    script: "bme280",
						args: "0x77",
					},
				]
			},
		},
```

**Comment by BKeyport** [comment]
I seem to recall you mentioning adafruit's modules - apparently they have
it set to 0x77 by default, then if you jump two pins (SDO and ground) on
the board, it'll move to 0x76. I only mentioned the error for those who
aren't script savvy (or don't read into Adafruit's docs like I do)

I like your "args" fix. This would be good for any module using
qwiic/stemmaQT/i2c - would solve any and all settable parts of HW modules.

**Comment by Tom-Hirschberger** [comment]
Perfect.
I will add an additional hint to the readme with some well known addresses.
